unique_ids:
  assets:
    standard-page.html: PPTFBAN7D5VRCM2M7RVYQM3T6A6LRK4N
    theme.css: CVBHJZIDLAXUHGWMVLQPTHZ7CSFN6QJB
  forms:
    Form1: 2WC7JO4V4T2EXRIQLU6U4RG23GTPNAM3
  modules: {}
  scripts: {}
  server_modules: {}
